disabled_rules:
  - cyclomatic_complexity

line_length:
  warning: 180
  error: 350
  ignores_comments: true
  ignores_urls: true

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 80
    error: 160
  excluded:
    - id
    - _fetchedResultsController
    - _tabBarController

nesting:
  type_level: 2

excluded:
  - Pods
