language: swift
os: osx
osx_image: xcode10.1

script:
  - swiftlint --strict
  - xcodebuild clean test -project HackIllinois.xcodeproj -scheme HackIllinois -destination "platform=iOS Simulator,OS=12.1,name=iPhone X"

