language: swift
os: osx
osx_image: xcode10.1

before_install:
    - pod repo update

script:
  - swiftlint --strict
  - xcodebuild clean build -workspace HackIllinois.xcworkspace -scheme HackIllinois -destination "platform=iOS Simulator,OS=12.1,name=iPhone X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

cache:
  - cocoapods
