name: Swift Lint and Build

on:
  push:
    paths:
      - '.github/workflows/ci.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

    branches: 
      - '**'



jobs:
  # TODO: Linting does not work still since it 
  # doesn't seem to be using the .swiftlint.yml file
  
  # lint:

  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Lint
  #     run: swiftlint 

  #   - name: Display the path
  #     run: ls -a
  #     shell: bash

  #   - name: Lint Test
  #     run: swiftlint lint --strict --config ./.swiftlint.yml
  lint:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: GitHub Action for SwiftLint (Only files changed in the PR)
          uses: norio-nomura/action-swiftlint@3.2.1
          env:
            DIFF_BASE: ${{ github.base_ref }}
          with:
            args: --strict

  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -project HackIllinois.xcodeproj -scheme HackIllinois -destination "platform=iOS Simulator,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
