name: Swift Lint and Build

on:
  #push:
    #branches: 
      #- '**'
  pull_request:
    branches: ["dev"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: GitHub Action for SwiftLint (Only files changed in the PR)
          uses: norio-nomura/action-swiftlint@3.2.1
          env:
            DIFF_BASE: ${{ github.base_ref }}
          with:
            args: --strict

  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -project HackIllinois.xcodeproj -scheme HackIllinois -destination "platform=iOS Simulator,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
